spring:
  application:
    name: NumBank-API
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/migration/V1__init_database.sql