spring:
  application:
    name: NumBank-API
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: public
    locations: classpath:db/migration
    enabled: true
logging:
  level:
    org:
      flywaydb: DEBUG